In [33]:
#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline/refs/heads/main/data/raw/tipos_seguro.csv"

tipos_seguro = pd.read_csv(url)
tipos_seguro.head()

   id_tipo_seguro        tipo     categoria riesgo_base
0               1        Pyme      Familiar           -
1               2  Industrial   Empresarial       4.68
2               3  Industrial      Familiar        5.10
3               4  Industrial      Personal         NaN
4               5        Auto  empresarial         9.07

In [8]:
#EXPLORACION DE DATOS

#tipos_seguro.shape #filas, columnas
#tipos_seguro.columns
#tipos_seguro.info()
#tipos_seguro.isnull().sum() #cuenta los valores nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_tipo_seguro  12 non-null     int64
 1   tipo            12 non-null     object
 2   categoria       10 non-null     object
 3   riesgo_base     10 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

In [34]:
#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(tipos_seguro):
    tipos_seguro.columns = (
        tipos_seguro.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return tipos_seguro

# Limpia solamente textos
def limpiar_texto(tipos_seguro):
    for col in tipos_seguro.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        tipos_seguro[col] = tipos_seguro[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        tipos_seguro[col] = tipos_seguro[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return tipos_seguro

#APLICA LIMPIEZA GENERAL
tipos_seguro = normalizar_columnas(tipos_seguro)
tipos_seguro = limpiar_texto(tipos_seguro)
tipos_seguro = tipos_seguro.drop_duplicates() #Elimina duplicados

In [36]:
#LIMPIEZA DE DATOS ESPECIFICOS

#Tipo
#Elimina caracteres especiales, tildes, acentos, ñ
import unicodedata
tipos_seguro["tipo"] = (
    tipos_seguro["tipo"]
    .astype(str)
    .apply(lambda x: unicodedata.normalize('NFKD', x)
           .encode('ascii', 'ignore')
           .decode('utf-8'))
    .str.title()
)

tipos_seguro["tipo"] = tipos_seguro["tipo"].str.title()

#Categoria
tipos_seguro['categoria'] = tipos_seguro['categoria'].fillna("No Especificado")
tipos_seguro['categoria'] = tipos_seguro['categoria'].str.title()

#Riesgo_Base
import numpy as np
col = tipos_seguro["riesgo_base"].astype(str).str.strip().str.lower() #Convierte columna a texto, quita espacios a extremos y vuelve minusculas
col = col.replace(r"^\s*-\s*$", np.nan, regex=True)
col = col.replace(["","none","nan","null"], np.nan)               #identifica datos basura a verdaderos nulos

#SOLO eliminar puntos si hay coma (formato europeo)
col = col.apply(
    lambda x: x.replace(".", "").replace(",", ".")
    if isinstance(x, str) and "," in x
    else x
)

tipos_seguro["riesgo_base"] = pd.to_numeric(col, errors="coerce")     #Convierte a tipo numerico y si da error vuelve valor nulo

In [38]:
#SEPARAR DATOS INVALIDOS Y RECHAZADOS

columnas = ['id_tipo_seguro','tipo','categoria','riesgo_base']

datos_invalidos =(
    tipos_seguro[columnas].isin(["No Especificado"]).any(axis=1)|
    tipos_seguro[columnas].isna().any(axis=1)
)

tipos_seguro_validos = tipos_seguro[~datos_invalidos].copy()
tipos_seguro_rechazados = tipos_seguro[datos_invalidos].copy()

In [39]:
#MOTIVO DE RECHAZO

# MOTIVO DE RECHAZO

def motivo(row):
    columnas = {
        "id_tipo_seguro": "idTipoSeguro_invalido",
        "tipo": "tipo_invalido",
        "categoria": "categoria_invalido",
        "riesgo_base": "riesgoBase_invalido"
    }

    motivos = []

    for col, error in columnas.items():
        valor = row[col]

        # condición: nulo o "No Especificado"
        if pd.isna(valor) or str(valor).strip().lower() == "no especificado":
            motivos.append(error)

    return ";".join(motivos)

# aplicar a rechazados
tipos_seguro_rechazados["motivo_rechazo"] = tipos_seguro_rechazados.apply(motivo, axis=1)

In [43]:
#VERIFICAR SI HAY DATOS NULOS
#print(tipos_seguro["categoria"] == "No Especificado")
#tipos_seguro_rechazados["motivo_rechazo"].value_counts()

In [44]:
#EXPORTAR ARCHIVOS

tipos_seguro_validos.to_csv("tipos_seguro_curated.csv", index=False)

tipos_seguro_rechazados.to_csv("tipos_seguro_rejects.csv", index=False)

In [45]:
#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 37.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [46]:
engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [47]:
#CARGAR DATOS EN PostgreSQL

if tipos_seguro_validos.empty:
    print("⚠ No hay datos válidos")

if tipos_seguro_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    tipos_seguro_validos.to_sql('tipos_seguro_curated', engine, if_exists='append', index=False)
    tipos_seguro_rechazados.to_sql('tipos_seguro_rejects', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

Carga exitosa ✅

In [50]:
#VALIDAR LA CARGA

pd.read_sql(
    "SELECT*FROM tipos_seguro_curated LIMIT 10",
    engine
)

   id_tipo_seguro        tipo    categoria  riesgo_base
0               2  Industrial  Empresarial         4.68
1               3  Industrial     Familiar         5.10
2               5        Auto  Empresarial         9.07
3               6  Industrial  Empresarial         2.52
4               7       Salud     Personal         0.92
5               8   Educacion  Empresarial         7.42
6              10      Dental     Especial         2.70
7              11        Auto  Empresarial         4.33