In [38]:
#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline/refs/heads/main/data/raw/clientes.csv"

clientes = pd.read_csv(url)
clientes.head()

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [15]:
#EXPLORACION DE DATOS

#clientes.shape #filas, columnas
#clientes.columns
#clientes.info()
#clientes.isnull().sum() #cuenta los valores nulos

id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [39]:
#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(clientes):
    clientes.columns = (
        clientes.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return clientes

# Limpia solamente textos
def limpiar_texto(clientes):
    for col in clientes.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        clientes[col] = clientes[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        clientes[col] = clientes[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return clientes

#APLICA LIMPIEZA GENERAL
clientes = normalizar_columnas(clientes)
clientes = limpiar_texto(clientes)
clientes=clientes.drop_duplicates() #Elimina duplicados

In [70]:
from pandas.core.tools.datetimes import to_datetime
#LIMPIEZA DE DATOS ESPECIFICOS

#Nombre
import unicodedata

clientes["nombre"] = (
    clientes["nombre"]
    .astype(str)
    .apply(lambda x: unicodedata.normalize('NFKD', x)
           .encode('ascii', 'ignore')
           .decode('utf-8'))
    .str.title()
)

#Email
clientes["email"] = clientes["email"].astype(str).str.lower().str.strip()

#Genero
clientes["genero"] = (
    clientes ["genero"].astype(str).str.strip().str.lower().map({
        "hombre":"Masculino",
        "masculino":"Masculino",
        "m":"Masculino",
        "mujer":"Femenino",
        "femenino":"Femenino",
        "f":"Femenino",
        "fem":"Femenino",
        "female":"Femenino"
    })
)

#Ciudad
clientes["ciudad"] = (
    clientes["ciudad"].astype(str).str.strip().str.lower().replace({
        "sanmiguel":"san miguel",
        "s. miguel":"san miguel",
        "sta. ana":"santa ana",
        "staana":"santa ana",
        "santaana":"santa ana",
        "ss":"san salvador",
        "sansalvador": "san salvador",
        "lalibertad":"la libertad",
        "l. libertad":"la libertad",
        "sonso":"sonsonate"
        }).str.title()
)


#Fecha de nacimiento
clientes["fecha_nacimiento"] = pd.to_datetime(clientes["fecha_nacimiento"],errors="coerce",dayfirst=False)

#Segmento
clientes["segmento"] = clientes["segmento"].fillna("No especificado")

clientes = clientes[["id_cliente","nombre","email","genero","fecha_nacimiento","ciudad","segmento"]].replace(
    ["", " ", "NULL", "null", "None", "nan"],
    pd.NA
)

In [71]:
#SEPARAR DATOS INVALIDOS Y RECHAZADOS

clientes_validos=clientes[
    clientes['id_cliente'].notna()&
    clientes['nombre'].notna()&
    clientes['email'].notna()&
    clientes['genero'].notna()&
    clientes['fecha_nacimiento'].notna()&
    clientes['ciudad'].notna()&
    clientes['segmento'].notna()
].copy()


clientes_rechazados=clientes[
    clientes["id_cliente"].isna() |
    clientes['nombre'].isna() |
    clientes['email'].isna() |
    clientes['genero'].isna() |
    clientes['fecha_nacimiento'].isna() |
    clientes['ciudad'].isna() |
    clientes['segmento'].isna()
].copy()

In [76]:
#MOTIVO DE RECHAZO

def motivo(row):
  motivos=[]

  if pd.isna(row['id_cliente']):
    motivos.append("idCliente_vacio")

  if pd.isna(row['nombre']):
    motivos.append("nombre_vacio")

  if pd.isna(row['email']):
    motivos.append("email_vacio")

  if pd.isna(row['genero']):
    motivos.append("genero_vacio")

  if pd.isna(row['fecha_nacimiento']):
    motivos.append("fechaNacimiento_vacio")

  if pd.isna(row['ciudad']):
    motivos.append("ciudad_vacio")

  if pd.isna(row['segmento']):
    motivos.append("segmento_vacio")

  return ";".join(motivos)

clientes_rechazados["motivo_rechazo"] = clientes_rechazados.apply(motivo,axis=1)

In [78]:
#VERIFICAR SI HAY DATOS NULOS
print(clientes.isna().sum())

id_cliente             0
nombre                 0
email                  0
genero               595
fecha_nacimiento    2445
ciudad                 0
segmento               0
dtype: int64

In [77]:
#EXPORTAR ARCHIVOS

clientes_validos.to_csv("clientes_curated.csv", index=False)

clientes_rechazados.to_csv("clientes_rejects.csv", index=False)

In [79]:
#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [81]:
engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

In [82]:
test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [83]:
#CARGAR DATOS EN PostgreSQL

clientes_validos.to_sql(
    'clientes_curated',
    engine,
    if_exists='append',
    index=False
)

clientes_rechazados.to_sql(
    'clientes_rejects',
    engine,
    if_exists='append',
    index=False
)

555

In [84]:
#VALIDAR LA CARGA

pd.read_sql(
    "SELECT*FROM clientes_curated LIMIT 10",
    engine
)

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,Jose Chavez Perez,jose.chavez.perez1@gmail.com,Masculino,2011-11-24,San Miguel,No especificado
1,6,Ricardo Lopez Vasquez,ricardo.lopez.vasquez6@seguro.sv,Masculino,1966-10-15,Sonsonate,pyme
2,13,Carlos Santos Morales,carlos.santos.morales6@correo.com,Masculino,1975-08-02,Santa Ana,regular
3,17,Diego Garcia Flores,diego.garcia.flores3@seguro.sv,Femenino,1980-06-10,La Libertad,vip
4,20,Paula Lopez Garcia,paula.lopez.garcia6@correo.com,Femenino,1966-05-25,San Miguel,No especificado
5,28,Paula Castillo Santos,paula.castillo.santos0@gmail.com,Femenino,1978-06-21,San Salvador,premium
6,33,Ricardo Chavez Garcia,ricardo.chavez.garcia5@seguro.sv,Femenino,1993-08-26,San Miguel,vip
7,46,Daniela Santos Reyes,daniela.santos.reyes4@seguro.sv,Masculino,1949-01-01,La Libertad,premium
8,47,Andres Perez Garcia,andres.perez.garcia5@example.com,Femenino,1982-02-13,La Libertad,regular
9,50,Marta Martinez Castillo,marta.martinez.castillo1@correo.com,Masculino,1972-02-28,La Libertad,premium