In [107]:
#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

aseguradoras = pd.read_csv(url)
aseguradoras.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [ ]:
#EXPLORACION DE DATOS

#aseguradoras.shape #filas, columnas
#aseguradoras.columns
#aseguradoras.info()
#aseguradoras.isnull().sum() #cuenta los valores nulos

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

In [108]:
#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(aseguradoras):
    aseguradoras.columns = (
        aseguradoras.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(r"\s+", "_", regex=True)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return aseguradoras

# Limpia solamente textos
def limpiar_texto(aseguradoras):
    for col in aseguradoras.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        aseguradoras[col] = aseguradoras[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        aseguradoras[col] = aseguradoras[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return aseguradoras

#APLICA LIMPIEZA GENERAL
aseguradoras = normalizar_columnas(aseguradoras)
aseguradoras = limpiar_texto(aseguradoras)
aseguradoras = aseguradoras.drop_duplicates() #Elimina duplicados

In [109]:
#LIMPIEZA DE DATOS ESPECIFICOS

#Nombre
aseguradoras["nombre"] = (
        aseguradoras["nombre"]
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(r"\s+", "_", regex=True)     #Cambia espacios en medio por _
        .str.title()
    )

#Pais
import unicodedata
aseguradoras["pais"] = aseguradoras["pais"].fillna("No Especificado")

aseguradoras["pais"] = (
    aseguradoras["pais"]
    .astype(str)
    .apply(lambda x: unicodedata.normalize('NFKD', x)
           .encode('ascii', 'ignore')
           .decode('utf-8'))
    .str.title()
)

aseguradoras["pais"] = (
    aseguradoras["pais"].astype(str).str.strip().str.lower().replace({
        "costarica":"costa rica",
        "elsalvador":"el salvador"
        }).str.title()
)


#Rating_riesgo
aseguradoras["rating_riesgo"] = (
    aseguradoras["rating_riesgo"].astype(str).str.strip().str.lower().map({
        "a":"alto",
        "alto":"alto",
        "m":"medio",
        "medio":"medio",
        "b":"bajo",
        "bajo":"bajo"
        }).str.title()
)

aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].fillna("No Especificado")

In [110]:
#SEPARAR DATOS INVALIDOS Y RECHAZADOS

condicion = ["No Especificado"]

aseguradoras_validos = aseguradoras[
    ~aseguradoras[['id_aseguradora','nombre','pais','rating_riesgo']]
    .isin(condicion)
    .any(axis=1)
].copy()

aseguradoras_rechazados = aseguradoras[
    aseguradoras[['id_aseguradora','nombre','pais','rating_riesgo']]
    .isin(condicion)
    .any(axis=1)
].copy()

In [113]:
# MOTIVO DE RECHAZO

def motivo(row):
    motivos = []

    if row['id_aseguradora'] == "No Especificado":
        motivos.append("idAseguradora_noEspecificada")

    if row['nombre'] == "No Especificado":
        motivos.append("nombre_noEspecificado")

    if row['pais'] == "No Especificado":
        motivos.append("pais_noEspecificado")

    if row['rating_riesgo'] == "No Especificado":
        motivos.append("ratingRiesgo_noEspecificado")

    return ";".join(motivos)


# aplicar a rechazados
aseguradoras_rechazados["motivo_rechazo"] = aseguradoras_rechazados.apply(motivo, axis=1)

In [114]:
#EXPORTAR ARCHIVOS

aseguradoras_validos.to_csv("aseguradoras_curated.csv", index=False)

aseguradoras_rechazados.to_csv("aseguradoras_rejects.csv", index=False)

In [117]:
#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 34.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [118]:
engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [119]:
#CARGAR DATOS EN PostgreSQL

if aseguradoras_validos.empty:
    print("⚠ No hay datos válidos")

if aseguradoras_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    aseguradoras_validos.to_sql('aseguradoras_curated', engine, if_exists='append', index=False)
    aseguradoras_rechazados.to_sql('aseguradoras_rejects', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

Carga exitosa ✅

In [124]:
#VALIDAR LA CARGA

pd.read_sql(
    "SELECT*FROM aseguradoras_curated LIMIT 10",
    engine
)

   id_aseguradora          nombre         pais rating_riesgo
0               1   Aseguradora_1   Costa Rica          Alto
1               2   Aseguradora_2  El Salvador          Bajo
2               4   Aseguradora_4   Costa Rica         Medio
3               5   Aseguradora_5  El Salvador          Bajo
4               7   Aseguradora_7    Guatemala          Alto
5               8   Aseguradora_8       Panama          Bajo
6              12  Aseguradora_12  El Salvador          Bajo
7              13  Aseguradora_13     Honduras          Alto
8              15  Aseguradora_15  El Salvador          Alto