In [22]:
#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

polizas = pd.read_csv(url)
polizas.head(20)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [10]:
#EXPLORACION DE DATOS

#polizas.shape #filas, columnas
#polizas.columns
#polizas.info()
#polizas.isnull().sum() #cuenta los valores nulos

In [23]:
#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(polizas):
    polizas.columns = (
        polizas.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return polizas

# Limpia solamente textos
def limpiar_texto(polizas):
    for col in polizas.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        polizas[col] = polizas[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        polizas[col] = polizas[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return polizas

#APLICA LIMPIEZA GENERAL
polizas = normalizar_columnas(polizas)
polizas = limpiar_texto(polizas)
polizas = polizas.drop_duplicates() #Elimina duplicados

In [25]:
#LIMPIEZA DE DATOS ESPECIFICOS

#Fecha de emision
polizas["fecha_emision"] = polizas["fecha_emision"].astype(str).str.strip()
polizas["fecha_emision"] = pd.to_datetime(polizas["fecha_emision"],errors="coerce",dayfirst=True,infer_datetime_format=True)

#Metodo para tipos numericos float:
import numpy as np
def limpiar_monto(x):
    if not isinstance(x, str):
        return x

    # caso: formato europeo (1.234.567,89)
    if "," in x and "." in x:
        if x.rfind(",") > x.rfind("."):
            return x.replace(".", "").replace(",", ".")

    # caso: solo comas → miles (1,000,000)
    if x.count(",") > 1:
        return x.replace(",", "")

    # caso: una coma → decimal
    if "," in x:
        return x.replace(",", ".")

    return x


#Prima
col = polizas["prima"].astype(str).str.strip().str.lower()
# falsos nulos
col = col.replace(r"^\s*-\s*$", np.nan, regex=True)
col = col.replace(["", "none", "nan", "null"], np.nan)
col = col.apply(limpiar_monto)
polizas["prima"] = pd.to_numeric(col, errors="coerce")

#Comision
col = polizas["comision"].astype(str).str.strip().str.lower()
# falsos nulos
col = col.replace(r"^\s*-\s*$", np.nan, regex=True)
col = col.replace(["", "none", "nan", "null"], np.nan)
col = col.apply(limpiar_monto)
polizas["comision"] = pd.to_numeric(col, errors="coerce")

#Monto asegurado
col = polizas["monto_asegurado"].astype(str).str.strip().str.lower()
# falsos nulos
col = col.replace(r"^\s*-\s*$", np.nan, regex=True)
col = col.replace(["", "none", "nan", "null"], np.nan)
col = col.apply(limpiar_monto)
polizas["monto_asegurado"] = pd.to_numeric(col, errors="coerce")

/tmp/ipykernel_1386/3208220928.py:5: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  polizas["fecha_emision"] = pd.to_datetime(polizas["fecha_emision"],errors="coerce",dayfirst=True,infer_datetime_format=True)
/tmp/ipykernel_1386/3208220928.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  polizas["fecha_emision"] = pd.to_datetime(polizas["fecha_emision"],errors="coerce",dayfirst=True,infer_datetime_format=True)

In [29]:
#SEPARAR DATOS INVALIDOS Y RECHAZADOS
polizas_validos=polizas[
    polizas['fecha_emision'].notna()&
    polizas['prima'].notna()&
    polizas['comision'].notna()&
    polizas['monto_asegurado'].notna()
].copy()


polizas_rechazados=polizas[
    polizas["fecha_emision"].isna() |
    polizas['prima'].isna() |
    polizas['comision'].isna() |
    polizas['monto_asegurado'].isna()
].copy()

In [31]:
#MOTIVO DE RECHAZO

def motivo(row):
  motivos=[]

  if pd.isna(row['fecha_emision']):
    motivos.append("fechaEmision_vacia")

  if pd.isna(row['prima']):
    motivos.append("prima_vacia")

  if pd.isna(row['comision']):
    motivos.append("comision_vacia")

  if pd.isna(row['monto_asegurado']):
    motivos.append("montoAsegurado_vacio")

  return ";".join(motivos)

polizas_rechazados["motivo_rechazo"] = polizas_rechazados.apply(motivo,axis=1)

In [33]:
#VERIFICAR SI HAY DATOS NULOS
#print(polizas.isna().sum())
#polizas
#polizas_rechazados["motivo_rechazo"].value_counts()

In [34]:
#EXPORTAR ARCHIVOS

polizas_validos.to_csv("polizas_curated.csv", index=False)

polizas_rechazados.to_csv("polizas_rejects.csv", index=False)

In [35]:
#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 39.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [36]:
engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [37]:
#CARGAR DATOS EN PostgreSQL

if polizas_validos.empty:
    print("⚠ No hay datos válidos")

if polizas_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    polizas_validos.to_sql('polizas_curated', engine, if_exists='append', index=False)
    polizas_rechazados.to_sql('polizas_rejects', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

Carga exitosa ✅

In [40]:
#VALIDAR LA CARGA

pd.read_sql(
    "SELECT*FROM polizas_curated LIMIT 10",
    engine
)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,4,2026-01-09,2821,40,10,5,1866.62,456.99,244461.27
1,7,2025-09-02,1254,25,11,4,1400.82,188.40,258202.93
2,10,2026-01-24,2281,69,13,3,791.38,67.44,20710.00
3,14,2026-01-20,367,65,1,11,0.00,122.12,249504.31
4,19,2025-05-19,1693,50,3,9,1257.43,237.20,106454.95
5,23,2025-03-21,61,19,3,5,1403.46,112.05,163649.61
6,26,2025-07-29,2295,71,11,4,614.46,149.78,36670.97
7,27,2025-06-25,352,30,3,6,-1290.55,179.37,162227.75
8,28,2025-02-21,1213,65,8,9,464.73,25.26,18041.73
9,36,2025-12-06,2313,53,12,6,779.35,64.18,95204.18