In [15]:
#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv"

corredores = pd.read_csv(url)
corredores.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [6]:
#EXPLORACION DE DATOS

#corredores.shape #filas, columnas
#corredores.columns
#corredores.info()
#corredores.isnull().sum() #cuenta los valores nulos

id_corredor           0
nombre                0
zona                 17
nivel                12
anios_experiencia     4
dtype: int64

In [16]:
#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(corredores):
    corredores.columns = (
        corredores.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return corredores

# Limpia solamente textos
def limpiar_texto(corredores):
    for col in corredores.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        corredores[col] = corredores[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        corredores[col] = corredores[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return corredores

#APLICA LIMPIEZA GENERAL
corredores = normalizar_columnas(corredores)
corredores = limpiar_texto(corredores)
corredores = corredores.drop_duplicates() #Elimina duplicados

In [17]:
#LIMPIEZA DE DATOS ESPECIFICOS

#nombre
import unicodedata

corredores["nombre"] = (
    corredores["nombre"]
    .astype(str)
    .apply(lambda x: unicodedata.normalize('NFKD', x)
           .encode('ascii', 'ignore')
           .decode('utf-8'))
    .str.title()
)

#zona
corredores["zona"] = (
    corredores ["zona"].astype(str).str.strip().str.lower().map({
        "occidente":"Occidental",
        "paracentral":"Paracentral",
        "costa":"Costa",
        "centro":"Central",
        "oriente":"Oriental"
    })
)

corredores["zona"] = corredores["zona"].fillna("No Especificado")

#nivel
corredores["nivel"] = (
    corredores ["nivel"].astype(str).str.strip().str.lower().map({
        "junior":"Junior",
        "mid":"Mid",
        "senior":"Senior"
    })
)

corredores["nivel"] = corredores["nivel"].fillna("No Especificado")

#anios_experiencia
corredores["anios_experiencia"] = pd.to_numeric(corredores["anios_experiencia"], errors="coerce")
corredores["anios_experiencia"] = corredores["anios_experiencia"].fillna("No Especificado")

In [18]:
#SEPARAR DATOS INVALIDOS Y RECHAZADOS

condicion = ["No Especificado"]

corredores_validos = corredores[
    ~corredores[['id_corredor','nombre','zona','nivel','anios_experiencia']]
    .isin(condicion)
    .any(axis=1)
].copy()

corredores_rechazados = corredores[
    corredores[['id_corredor','nombre','zona','nivel','anios_experiencia']]
    .isin(condicion)
    .any(axis=1)
].copy()

In [19]:
# MOTIVO DE RECHAZO

def motivo(row):
    motivos = []

    if row['id_corredor'] == "No Especificado":
        motivos.append("idCorredor_noEspecificado")

    if row['nombre'] == "No Especificado":
        motivos.append("nombre_noEspecificado")

    if row['zona'] == "No Especificado":
        motivos.append("zona_noEspecificada")

    if row['nivel'] == "No Especificado":
        motivos.append("nivel_noEspecificado")

    if row['anios_experiencia'] == "No Especificado":
        motivos.append("anios_experiencia_noEspecificados")

    return ";".join(motivos)


# aplicar a rechazados
corredores_rechazados["motivo_rechazo"] = corredores_rechazados.apply(motivo, axis=1)

In [20]:
#EXPORTAR ARCHIVOS

corredores_validos.to_csv("corredores_curated.csv", index=False)

corredores_rechazados.to_csv("corredores_rejects.csv", index=False)

In [22]:
#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 66.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [23]:
engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [24]:
#CARGAR DATOS EN PostgreSQL

if corredores_validos.empty:
    print("⚠ No hay datos válidos")

if corredores_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    corredores_validos.to_sql('corredores_curated', engine, if_exists='append', index=False)
    corredores_rechazados.to_sql('corredores_rejects', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

Carga exitosa ✅

In [25]:
#VALIDAR LA CARGA

pd.read_sql(
    "SELECT*FROM corredores_curated LIMIT 10",
    engine
)

   id_corredor                 nombre         zona   nivel  anios_experiencia
0            1      Jose Lopez Flores  Paracentral     Mid                4.0
1            2      Jose Ortiz Garcia      Central  Junior                0.0
2            3     Maria Ramirez Cruz      Central  Senior                6.0
3            8  Paula Ortiz Hernandez      Central  Junior               17.0
4            9  Carlos Torres Vasquez  Paracentral  Junior                2.0
5           13  Valeria Garcia Torres     Oriental  Senior               23.0
6           14     Diego Gomez Chavez      Central  Senior               20.0
7           16     Juan Reyes Morales        Costa  Junior                6.0
8           18     Paula Perez Flores     Oriental     Mid               23.0
9           19  Fernanda Ortiz Flores      Central  Senior               12.0