In [38]:
#CONEXION A .CSV GUARDADO EN GITHUB
import pandas as pd
import numpy as np
import re

url = "https://raw.githubusercontent.com/JGaray04/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"

siniestros = pd.read_csv(url)
siniestros.head(20)

    id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0              1      17400      16-10-2025         2092.59    ABIERTO
1              2       2465      01/08/2025        7,076.25    Abierto
2              3      15785      19-09-2025         702.27     cerrado
3              4      14299      27/09/2025         274.63     Abierto
4              5      12908      01/12/2025        9,377.69  Rechazado
5              6       5107      2026/02/10       10,535.74        NaN
6              7       3379      2025/08/16       10,513.30    Abierto
7              8      23824      17-01-2025         2736.20    ABIERTO
8              9      18118      2025/08/27             NaN    cerrado
9             10      19947      2025/09/12         8801.03    Cerrado
10            11       6448      31/05/2025        1.619,38    Abierto
11            12       4096      23/02/2026             NaN  Rechazado
12            13       3716      13-07-2025        -4274.39  Rechazado
13            14       8260      2025-09-08             NaN        NaN
14            15      19142      2025/01/29        14533.77    Abierto
15            16      16312      2025/10/02             NaN    ABIERTO
16            17       2112      2025-08-01       11.995,56    cerrado
17            18       4445        05-23-25               -        NaN
18            19       5547      2025-10-10        5714.06     cerrado
19            20      21508        08-29-25        8867.02         NaN

In [6]:
#EXPLORACION DE DATOS

#siniestros.shape #filas, columnas
#siniestros.columns
#siniestros.info()
#siniestros.isnull().sum() #cuenta los valores nulos

In [39]:
#LIMPIEZA DE DATOS GENERALES

def normalizar_columnas(siniestros):
    siniestros.columns = (
        siniestros.columns
        .str.strip()                            #Elimina espacios
        .str.lower()                            #Vuelve minuscula
        .str.replace(" ", "_", regex=False)     #Cambia espacios en medio por _
        .str.replace(r"[^\w]", "", regex=True)  # elimina caracteres raros
    )
    return siniestros

# Limpia solamente textos
def limpiar_texto(siniestros):
    for col in siniestros.select_dtypes(include="object").columns: #Selecciona solamente colunmas tipo texto
        siniestros[col] = siniestros[col].astype(str).str.strip().str.lower()  #Convierte a texto, elimina espacios y vuelve minusculas

        siniestros[col] = siniestros[col].replace(
            ["nan", "None", "null", ""],              #Cambia valores nulos por verdaderos vacios
            pd.NA
        )
    return siniestros

#APLICA LIMPIEZA GENERAL
siniestros = normalizar_columnas(siniestros)
siniestros = limpiar_texto(siniestros)
siniestros = siniestros.drop_duplicates() #Elimina duplicados

In [50]:
#LIMPIEZA DE DATOS ESPECIFICOS

#Fecha Siniestros
siniestros["fecha_siniestro"] = pd.to_datetime(
    siniestros["fecha_siniestro"],
    errors="coerce",
    format="mixed"
)

#Monto Siniestros
def limpiar_monto(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip().lower()

    # falsos nulos
    if x in ["", "-", "none", "nan", "null"]:
        return np.nan

    # eliminar símbolos (moneda, letras)
    x = re.sub(r"[^\d,.\-]", "", x)

    if "," in x and "." in x:
        # europeo → coma decimal
        if x.rfind(",") > x.rfind("."):
            x = x.replace(".", "").replace(",", ".")
        else:
            x = x.replace(",", "")

    elif x.count(",") > 1:
        # miles con comas
        x = x.replace(",", "")

    elif "," in x:
        # decimal con coma
        x = x.replace(",", ".")

    return x

col = siniestros["monto_siniestro"].apply(limpiar_monto)
siniestros["monto_siniestro"] = pd.to_numeric(col, errors="coerce")

#Estado
siniestros["estado"] = (
    siniestros["estado"].astype(str).str.strip().str.lower().map({
        "abierto":"Abierto",
        "cerrado":"Cerrado",
        "rechazado":"Rechazado"
        })
)

siniestros["estado"] = siniestros["estado"].fillna("No Especificado")

In [63]:
#print(siniestros["monto_siniestro"].astype(str).value_counts().head(20))
#siniestros
#print(siniestros["monto_siniestro"].isna().sum())
#print(siniestros["fecha_siniestro"].isna().sum())
#print(siniestros["estado"].astype(str).value_counts().head(20))

In [69]:
#SEPARAR DATOS INVALIDOS Y RECHAZADOS

columnas = ['fecha_siniestro','monto_siniestro','estado']

datos_invalidos =(
    siniestros[columnas].isin(["No Especificado"]).any(axis=1)|
    siniestros[columnas].isna().any(axis=1)
)

siniestros_validos = siniestros[~datos_invalidos].copy()
siniestros_rechazados = siniestros[datos_invalidos].copy()

In [70]:
# MOTIVO DE RECHAZO

def motivo(row):
    columnas = {
        "fecha_siniestro": "fechaSiniestro_invalida",
        "monto_siniestro": "montoSiniestro_invalido",
        "estado": "estado_invalido"
    }

    motivos = []

    for col, error in columnas.items():
        valor = row[col]

        # condición: nulo o "No Especificado"
        if pd.isna(valor) or str(valor).strip().lower() == "no especificado":
            motivos.append(error)

    return ";".join(motivos)

# aplicar a rechazados
siniestros_rechazados["motivo_rechazo"] = siniestros_rechazados.apply(motivo, axis=1)

In [72]:
#VERIFICAR SI HAY DATOS NULOS
#print(siniestros["estado"] == "No Especificado")
#siniestros_rechazados["motivo_rechazo"].value_counts()

In [73]:
#EXPORTAR ARCHIVOS

siniestros_validos.to_csv("siniestros_curated.csv", index=False)

siniestros_rechazados.to_csv("siniestros_rejects.csv", index=False)

In [74]:
#CONECTAR A POSTGRESQL CLOUD
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 90.1 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [75]:
engine = create_engine("postgresql://etl_user_user:6pkRr0giJ1JmO2LATPOR77QtJLyPRgJr@dpg-d6ue8l450q8c73fvs7b0-a.oregon-postgres.render.com/etl_user")

test = pd.read_sql("SELECT 1", engine)
print(test)

   ?column?
0         1

In [76]:
#CARGAR DATOS EN PostgreSQL

if siniestros_validos.empty:
    print("⚠ No hay datos válidos")

if siniestros_rechazados.empty:
    print("⚠ No hay datos rechazados")

try:
    siniestros_validos.to_sql('siniestros_curated', engine, if_exists='append', index=False)
    siniestros_rechazados.to_sql('siniestros_rejects', engine, if_exists='append', index=False)
    print("Carga exitosa ✅")
except Exception as e:
    print("Error en carga ❌:", e)

Carga exitosa ✅

In [78]:
#VALIDAR LA CARGA

pd.read_sql(
    "SELECT*FROM siniestros_rejects LIMIT 10",
    engine
)

,id_siniestro,id_poliza,fecha_siniestro,monto_siniestro,estado,motivo_rechazo
0,6,5107,2026-02-10,10535.74,No Especificado,estado_invalido
1,9,18118,2025-08-27,NaN,Cerrado,montoSiniestro_invalido
2,12,4096,2026-02-23,NaN,Rechazado,montoSiniestro_invalido
3,14,8260,2025-09-08,NaN,No Especificado,montoSiniestro_invalido;estado_invalido
4,16,16312,2025-10-02,NaN,Abierto,montoSiniestro_invalido
5,18,4445,2025-05-23,NaN,No Especificado,montoSiniestro_invalido;estado_invalido
6,20,21508,2025-08-29,8867.02,No Especificado,estado_invalido
7,25,719,2025-12-25,3257.92,No Especificado,estado_invalido
8,27,22625,2025-07-03,141.77,No Especificado,estado_invalido
9,28,3123,2025-10-08,NaN,Cerrado,montoSiniestro_invalido